import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import LeftSidebar from "@/components/LeftSidebar";
import MainContent from "@/components/MainComponents";
import RightSidebar from "@/components/RightSidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {/* {children} */}
        <div className="flex h-screen bg-gray-100">
          <LeftSidebar />
          <div className="flex-1 overflow-auto">
            <Header />
            <MainContent />
          </div>
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}


